const prompts = [
  "descrivi la tua giornata in quattro parole",
  "una frase da non dire a Salvini",
  "lo slogan della tua campagna elettorale",
  "la tua prima frase come presidente",
  "frase da non dire mentre ti fanno una multa",
  "una cosa a cui pensare durante un rapporto sessuale noioso",
  "un indizio che la tua casa è maledetta",
  "un buon modo per farsi licenziare",
  "il nome della tua nuova invenzione",
  "una frase per rompere il ghiaccio ad una party",
  "una scusa per riportare in vita Mussolini",
  "un tweet di un uomo di neandertal",
  "una recensione che daresti a questo gioco",
  "un'attrazione turistica all'inferno",
  "cosa divertente da fare se rinchiuso nel centro commerciale di notte",
  "un graffiti che troveresti in un asilo",
  "se Dio ha il senso dell'umorismo, accoglie le persone in paradiso dicendo:",
  "le ultime parole di Gesù",
  "inventa una nuova teoria cospirazionistica",
  "cosa da non fare ad un primo appuntamento",
  "il mondo sarebbe un posto migliore se...",
  "la cosa migliore di vivere in corea del nord",
  "Il crimine che commetteresti se potessi farla franca",
  "Il primo comandamento nella nuova religione che hai creato",
  "L'ultima persona che inviteresti alla tua festa di compleanno",
  "Il più fantastico Guinness World Record da battere",
  "Il peggior costume di Halloween per un bambino",
  "Il peggior nome per un'impresa di pompe funebri",
  "Il peggior nome per un trapper",
  "Inventa un nuovo gusto della pizza",
  "cosa direbbero i gatti se potessero parlare?",
  "come fossero i giocatori senza denti?",
  "da dove prende la carne il mcdonald?",
  "da dove vengono i bambini?",
  "l'unica cosa che ti ricordi di quando eri nell'utero",
  "onestamente, non si possono mai avere troppi...",
  "sai che un ristorante fa schifo quando il cameriere ti dice...",
  "una parolaccia che nessuno usa più",
  "la cosa peggiore da indossare durante una maratona",
  "capisci di essere nel quartiere sbagliato quando uno ti dice...",
  "non c'è nulla di più sexy di...",
  "il modo peggiore di finire una storia paurosa",
  "la domanda più stupida su Yahoo",
  "la peggiore frase per lasciarsi: ",
  "il nome che verrà dato alla generazione futura",
  "frase mai scritta su internet",
  "una cosa che il papa ti venderebbe",
  "il nome di una gang di vecchiarelle",
  "odi san valentino? Ora esiste una nuova festa chiamata...",
  "il nome della tua nuova app di incontri",
  "il titolo di un video chiaramente clickbait",
  "cosa che leggeresti sul foglio illustrativo di un medicinale: Può causare...",
  "il nome della tua nuova marca di preservativi",
  "frase che non vorresti sentire dal tuo uber driver",
  "L'Italia è il paese numero uno al mondo per quanto riguarda",
];

module.exports = prompts;
